# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(526, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 60, 321, 141))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.return_min = QtWidgets.QDoubleSpinBox(self.widget)
        self.return_min.setObjectName("return_min")
        self.gridLayout.addWidget(self.return_min, 1, 1, 1, 1)
        self.return_max = QtWidgets.QDoubleSpinBox(self.widget)
        self.return_max.setObjectName("return_max")
        self.gridLayout.addWidget(self.return_max, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.return_maxdrawdown_min = QtWidgets.QDoubleSpinBox(self.widget)
        self.return_maxdrawdown_min.setObjectName("return_maxdrawdown_min")
        self.gridLayout.addWidget(self.return_maxdrawdown_min, 2, 1, 1, 1)
        self.return_maxdrawdown_max = QtWidgets.QDoubleSpinBox(self.widget)
        self.return_maxdrawdown_max.setObjectName("return_maxdrawdown_max")
        self.gridLayout.addWidget(self.return_maxdrawdown_max, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.return_sharp_min = QtWidgets.QDoubleSpinBox(self.widget)
        self.return_sharp_min.setObjectName("return_sharp_min")
        self.gridLayout.addWidget(self.return_sharp_min, 3, 1, 1, 1)
        self.return_sharp_max = QtWidgets.QDoubleSpinBox(self.widget)
        self.return_sharp_max.setObjectName("return_sharp_max")
        self.gridLayout.addWidget(self.return_sharp_max, 3, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(370, 90, 121, 122))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dis_shouyi = QtWidgets.QPushButton(self.widget1)
        self.dis_shouyi.setEnabled(True)
        self.dis_shouyi.setObjectName("dis_shouyi")
        self.verticalLayout.addWidget(self.dis_shouyi)
        self.dis_zuidahuiche = QtWidgets.QPushButton(self.widget1)
        self.dis_zuidahuiche.setObjectName("dis_zuidahuiche")
        self.verticalLayout.addWidget(self.dis_zuidahuiche)
        self.dis_sharp = QtWidgets.QPushButton(self.widget1)
        self.dis_sharp.setObjectName("dis_sharp")
        self.verticalLayout.addWidget(self.dis_sharp)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.return_min, self.return_max)
        MainWindow.setTabOrder(self.return_max, self.return_maxdrawdown_min)
        MainWindow.setTabOrder(self.return_maxdrawdown_min, self.return_maxdrawdown_max)
        MainWindow.setTabOrder(self.return_maxdrawdown_max, self.return_sharp_min)
        MainWindow.setTabOrder(self.return_sharp_min, self.return_sharp_max)
        MainWindow.setTabOrder(self.return_sharp_max, self.dis_shouyi)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "最小值"))
        self.label_5.setText(_translate("MainWindow", "最大值"))
        self.label.setText(_translate("MainWindow", "收益"))
        self.label_2.setText(_translate("MainWindow", "最大回撤"))
        self.label_3.setText(_translate("MainWindow", "sharp"))
        self.dis_shouyi.setText(_translate("MainWindow", "显示收益"))
        self.dis_zuidahuiche.setText(_translate("MainWindow", "显示最大回撤"))
        self.dis_sharp.setText(_translate("MainWindow", "显示sharp"))

